[versions]
jacoco = "0.8.7"
micronaut = "4.9.2"
micronaut-plugin = "4.5.4"
release-plugin = "1.18.16"

[libraries]
# renovate hint
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
gradle-plugin-micronaut = { group = "io.micronaut.gradle", name = "micronaut-platform-catalog-plugin", version.ref = "micronaut-plugin" }
gradle-plugin-release = { group = "pl.allegro.tech.build", name = "axion-release-plugin", version.ref = "release-plugin" }
gradle-plugin-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "7.2.1" }

[plugins]
git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.4.2" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut-plugin" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugin" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut-plugin" }
release = { id = "pl.allegro.tech.build.axion-release", version.ref = "release-plugin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
